
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EXIT = 20;
  public static final int STOP = 19;
  public static final int ATOME = 26;
  public static final int LSEYN = 7;
  public static final int AROBASE = 16;
  public static final int RPAREN = 4;
  public static final int IN = 18;
  public static final int PARALLELE = 13;
  public static final int SEMI = 2;
  public static final int LPAREN = 3;
  public static final int LBRACKET = 10;
  public static final int SEQUENTIELLE = 6;
  public static final int PARARELLEP = 12;
  public static final int RBRACKET = 11;
  public static final int CHOICE = 9;
  public static final int EMISSION = 22;
  public static final int DELTA = 15;
  public static final int COMMA = 5;
  public static final int EOF = 0;
  public static final int TIME = 27;
  public static final int RCROSS = 25;
  public static final int error = 1;
  public static final int RSEYN = 8;
  public static final int ASSIGN = 14;
  public static final int HIDE = 21;
  public static final int RECEPTION = 23;
  public static final int INTERUPT = 17;
  public static final int LCROSS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "SEQUENTIELLE",
  "LSEYN",
  "RSEYN",
  "CHOICE",
  "LBRACKET",
  "RBRACKET",
  "PARARELLEP",
  "PARALLELE",
  "ASSIGN",
  "DELTA",
  "AROBASE",
  "INTERUPT",
  "IN",
  "STOP",
  "EXIT",
  "HIDE",
  "EMISSION",
  "RECEPTION",
  "LCROSS",
  "RCROSS",
  "ATOME",
  "TIME"
  };
}

